mybatis:
  mapper-locations: classpath:/mapper/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# mysql
spring:
  # 分库分表shardingjdbc配置
  shardingsphere:
    dataSource:
      names: sharding0
      sharding0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.1.83:3306/sharding0?useUnicode=true&charsetEncoding=utf8&autoReconnect=true&useSSL=true
        username: root
        password: Tech@2018
    #      sharding1:
    #        type: com.alibaba.druid.pool.DruidDataSource
    #        driver-class-name: com.mysql.jdbc.Driver
    #        url: jdbc:mysql://192.168.1.83:3306/sharding1?useUnicode=true&charsetEncoding=utf8&autoReconnect=true&useSSL=true
    #        username: root
    #        password: Tech@2018
    sharding:
      default-data-source-name: sharding0
      tables:
        user:
          actual-data-nodes: sharding0.user_${[201910,201911,201912]}
          table-strategy:
            standard:
              sharding-column: create_time
              # 范围算法 between and
              rangeAlgorithmClassName: com.heling.rule.CreateTimeTableRangeShardingAlgorithm
              # 精准算法 = 、 in
              preciseAlgorithmClassName: com.heling.rule.CreateTimeTableShardingAlgorithm

