## mysql
#spring:
#  # 分库分表shardingjdbc配置
#  shardingsphere:
#    dataSource:
#      names: sharding0,sharding1
#      sharding0:
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.mysql.jdbc.Driver
#        url: jdbc:mysql://localhost:3306/sharding0?useUnicode=true&charsetEncoding=utf8&autoReconnect=true&useSSL=true
#        username: root
#        password: root
#      sharding1:
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.mysql.jdbc.Driver
#        url: jdbc:mysql://localhost:3306/sharding1?useUnicode=true&charsetEncoding=utf8&autoReconnect=true&useSSL=true
#        username: root
#        password: root
#    sharding:
#      tables:
#        user:
#          database-strategy:
#            standard:
#              sharding-column: name
#              # 自定义user表分库规则
#              precise-algorithm-class-name: com.heling.rule.UserDatabaseShardingAlgorithm
#          actual-data-nodes: sharding$->{0..1}.user_->${0..1}
#          table-strategy:
#            inline:
#              sharding-column: id
#              algorithm-expression: user_$->{id % 2}
#      default-data-source-name: sharding0
#
#
#mybatis:
#  mapper-locations: classpath:/mapper/*.xml
#
